# Generated by Django 4.0.1 on 2022-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=30)),
            ],
        ),
    ]
