# Generated by Django 4.0.1 on 2022-03-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='cena',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
