# Generated by Django 4.0.1 on 2022-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumenti', '0002_instrument_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='cena',
            field=models.IntegerField(),
        ),
    ]
