# Generated by Django 4.0.1 on 2022-03-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumenti', '0003_alter_instrument_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='cena',
            field=models.CharField(max_length=30),
        ),
    ]
