# Generated by Django 4.0.1 on 2022-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumenti', '0007_nalozi'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalozi',
            name='lozinka',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
