# Generated by Django 4.0.1 on 2022-03-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumenti', '0008_nalozi_lozinka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalozi',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
